### ISSUE TITLE
Meta+D

### ISSUE THREAD

**Issue by maverick74** [antroids/application-title-bar#38]
If it's set to "hide and keep space", with windows open, if you meta+d (to minimize all), buttons do not hide in my PC!

Can anyone reproduce it?

**Comment by antroids** [comment]
Yes, it's a bug in the Widget, because Task Manager works well.
The same issue with "Peek To Desktop" button.

**Comment by antroids** [comment]
I'll look further into it, but probably this bug cannot be fixed without decent integration with DBus.
For now I cannot see the difference between "Peek at Desktop" state and the display without focus in tasks model.
You can change "Active Task Source" to "Active task" in case you have single display setup.

**Comment by maverick74** [comment]
> You can change "Active Task Source" to "Active task" in case you have single display setup.

I'm not on the PC, but I have it set to "last active task" (if I'm understanding you right and we're talking about the same setting)

**Comment by luisbocanegra** [comment]
There is a dbus method to query the active effects `qdbus org.kde.KWin.Effect.WindowView1 /Effects org.kde.kwin.Effects.activeEffects`, you could use that do detect "Peek at Desktop" (which is is a desktop effect called [windowaperture](https://github.com/KDE/kwin/tree/master/src/plugins/windowaperture)) but not "Eye on Screen", because that one shows the effect as active only for a brief time

I know this way isn't clean because it requires constant monitoring but it's what I've been using in my applets/wallpapers and it seems to work fine.

**Comment by luisbocanegra** [comment]
Ah yeah, I forgot that one 🤦‍♂️ yes I tried it, but since I wanted to detect overview too (or any other effect) ended up going the dbus way, for your purposes it should work

**Comment by maverick74** [comment]
@antroids  does the mentioned commit solves this? Can it be closed?

Also, can you update the store.kde.org version to the latest???

(btw, in every release, here on github, there are never any mentions of what changed... is there any "special" reason?)

(sorry! lot's of questions...)

**Comment by antroids** [comment]
It would be better to test the feature first, then close the issue if everything ok. Nothing wrong if the issue will be opened for a while after a commit.
Updated. I was waiting for another issue. 
There is no integration with KDE store, so I have to fill release notes manually. Anyways, I have added autogenerated "Full Changelog" to the GitHub releases.

**Comment by maverick74** [comment]
thank you!!!

Will test but - so far - it's working as intended :)
